import type { Scc } from "./cluster-model.js";
/** OpenShift 4.22 defaults pinned to cluster-kube-apiserver-operator a18571de7438badd6206ba84f40a17160f524e94.
 * Nested-container description continuation indentation repaired; policy fields unchanged. */
export const defaultSccs = [
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: ["system:cluster-admins"],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "anyuid provides all features of the restricted SCC but allows users to run with any UID and any GID.",
      },
      name: "anyuid",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: 10,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["MKNOD"],
    runAsUser: {
      type: "RunAsAny",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: true,
    allowHostIPC: true,
    allowHostNetwork: true,
    allowHostPID: true,
    allowHostPorts: true,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "hostaccess allows access to all host namespaces but still requires pods to be run with a UID and SELinux context that are allocated to the namespace. WARNING: this SCC allows host access to namespaces, file systems, and PIDS.  It should only be used by trusted pods.  Grant with caution.",
      },
      name: "hostaccess",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["KILL", "MKNOD", "SETUID", "SETGID"],
    runAsUser: {
      type: "MustRunAsRange",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "hostPath",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: true,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "hostmount-anyuid-v2 provides all the features of the\nrestricted SCC but allows host mounts any UID, and any SELinux label by a pod.  This is primarily\nused by the persistent volume recycler. WARNING: this SCC allows host file\nsystem access as any UID, including UID 0.  Grant with caution.",
      },
      name: "hostmount-anyuid-v2",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["MKNOD"],
    runAsUser: {
      type: "RunAsAny",
    },
    seLinuxContext: {
      type: "RunAsAny",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "hostPath",
      "image",
      "nfs",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: true,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "hostmount-anyuid provides all the features of the\nrestricted SCC but allows host mounts and any UID by a pod.  This is primarily\nused by the persistent volume recycler. WARNING: this SCC allows host file\nsystem access as any UID, including UID 0.  Grant with caution.",
      },
      name: "hostmount-anyuid",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["MKNOD"],
    runAsUser: {
      type: "RunAsAny",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: ["system:serviceaccount:openshift-infra:pv-recycler-controller"],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "hostPath",
      "image",
      "nfs",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: true,
    allowHostPID: false,
    allowHostPorts: true,
    allowPrivilegeEscalation: false,
    allowPrivilegedContainer: false,
    allowedCapabilities: ["NET_BIND_SERVICE"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "kubernetes.io/description":
          "hostnetwork allows using host networking and host ports but still requires pods to be run with a UID and SELinux context that are allocated to the namespace. On top of the legacy 'hostnetwork' SCC, it also requires to drop ALL capabilities and does not allow privilege escalation binaries. It will also default the seccomp profile to runtime/default if unset, otherwise this seccomp profile is required.",
      },
      name: "hostnetwork-v2",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["ALL"],
    runAsUser: {
      type: "MustRunAsRange",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    seccompProfiles: ["runtime/default"],
    supplementalGroups: {
      type: "MustRunAs",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: true,
    allowHostPID: false,
    allowHostPorts: true,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "hostnetwork allows using host networking and host ports but still requires pods to be run with a UID and SELinux context that are allocated to the namespace.",
      },
      name: "hostnetwork",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["KILL", "MKNOD", "SETUID", "SETGID"],
    runAsUser: {
      type: "MustRunAsRange",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "MustRunAs",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: ["SETUID", "SETGID"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
      ranges: [
        {
          min: 0,
          max: 65534,
        },
      ],
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "kubernetes.io/description":
          'nested-container is specially tailored for running nested containers. It balances a tight security profile, while remaining loose enough to be useful to run nested containers in. In addition to requiring pods run with a user namespace, it allows SETUID and SETGID capabilities, requires the "container_engine_t" SELinux type, allows any users within the range of 0-65534, allows privilege escalation (to allow a container engine to run new{uid/gid}map), and allows any seccomp profile. Since any pods running within this SCC must use a user namespace ("hostUsers: false"), their actual UID/GID on the host will be allocated by the kubelet to be unprivileged, and any capabilities the pod is granted will not apply outside of the pods user namespace.',
      },
      name: "nested-container",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: null,
    runAsUser: {
      type: "MustRunAsRange",
      uidRangeMin: 0,
      uidRangeMax: 65534,
    },
    seLinuxContext: {
      type: "MustRunAs",
      seLinuxOptions: {
        type: "container_engine_t",
      },
    },
    seccompProfiles: ["*"],
    supplementalGroups: {
      type: "MustRunAs",
      ranges: [
        {
          min: 0,
          max: 65534,
        },
      ],
    },
    users: [],
    userNamespaceLevel: "RequirePodLevel",
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: false,
    allowPrivilegedContainer: false,
    allowedCapabilities: ["NET_BIND_SERVICE"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "kubernetes.io/description":
          "nonroot provides all features of the restricted SCC but allows users to run with any non-root UID.  The user must specify the UID or it must be specified on the by the manifest of the container runtime. On top of the legacy 'nonroot' SCC, it also requires to drop ALL capabilities and does not allow privilege escalation binaries. It will also default the seccomp profile to runtime/default if unset, otherwise this seccomp profile is required.",
      },
      name: "nonroot-v2",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["ALL"],
    runAsUser: {
      type: "MustRunAsNonRoot",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    seccompProfiles: ["runtime/default"],
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "nonroot provides all features of the restricted SCC but allows users to run with any non-root UID.  The user must specify the UID or it must be specified on the by the manifest of the container runtime.",
      },
      name: "nonroot",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["KILL", "MKNOD", "SETUID", "SETGID"],
    runAsUser: {
      type: "MustRunAsNonRoot",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: true,
    allowHostIPC: true,
    allowHostNetwork: true,
    allowHostPID: true,
    allowHostPorts: true,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: true,
    allowedCapabilities: ["*"],
    allowedUnsafeSysctls: ["*"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "RunAsAny",
    },
    groups: ["system:cluster-admins", "system:nodes", "system:masters"],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "privileged allows access to all privileged and host features and the ability to run as any user, any group, any fsGroup, and with any SELinux context.  WARNING: this is the most relaxed SCC and should be used only for cluster administration. Grant with caution.",
      },
      name: "privileged",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: null,
    runAsUser: {
      type: "RunAsAny",
    },
    seLinuxContext: {
      type: "RunAsAny",
    },
    seccompProfiles: ["*"],
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [
      "system:admin",
      "system:serviceaccount:openshift-infra:build-controller",
    ],
    volumes: ["*"],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: false,
    allowPrivilegedContainer: false,
    allowedCapabilities: ["NET_BIND_SERVICE"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "kubernetes.io/description":
          "restricted-v2 denies access to all host features and requires pods to be run with a UID, and SELinux context that are allocated to the namespace. This is the most restrictive SCC and it is used by default for authenticated users. On top of the legacy 'restricted' SCC, it also requires to drop ALL capabilities and does not allow privilege escalation binaries. It will also default the seccomp profile to runtime/default if unset, otherwise this seccomp profile is required.",
      },
      name: "restricted-v2",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["ALL"],
    runAsUser: {
      type: "MustRunAsRange",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    seccompProfiles: ["runtime/default"],
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: false,
    allowPrivilegedContainer: false,
    allowedCapabilities: ["NET_BIND_SERVICE"],
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
      ranges: [
        {
          min: 1000,
          max: 65534,
        },
      ],
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "kubernetes.io/description":
          "restricted-v3 denies access to all host features and requires pods to be run with user namespace (and may not be root within that user namespace), and SELinux context that are allocated to the namespace. This is the most restrictive SCC. On top of the legacy 'restricted' SCC, it also requires to drop ALL capabilities and does not allow privilege escalation binaries. It will also default the seccomp profile to runtime/default if unset, otherwise this seccomp profile is required. On top of the legacy 'restricted-v2' SCC, it requires a pod runs in a user namespace. Because of this, the pod to be any non-root UID within the user namespace (between 1000-65534), and it will still be unprivileged outside of the user namespace.",
      },
      name: "restricted-v3",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["ALL"],
    runAsUser: {
      type: "MustRunAsRange",
      uidRangeMin: 1000,
      uidRangeMax: 65534,
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    seccompProfiles: ["runtime/default"],
    supplementalGroups: {
      type: "MustRunAs",
      ranges: [
        {
          min: 1000,
          max: 65534,
        },
      ],
    },
    users: [],
    userNamespaceLevel: "RequirePodLevel",
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
  {
    allowHostDirVolumePlugin: false,
    allowHostIPC: false,
    allowHostNetwork: false,
    allowHostPID: false,
    allowHostPorts: false,
    allowPrivilegeEscalation: true,
    allowPrivilegedContainer: false,
    allowedCapabilities: null,
    apiVersion: "security.openshift.io/v1",
    defaultAddCapabilities: null,
    fsGroup: {
      type: "MustRunAs",
    },
    groups: [],
    kind: "SecurityContextConstraints",
    metadata: {
      annotations: {
        "include.release.openshift.io/ibm-cloud-managed": "true",
        "include.release.openshift.io/self-managed-high-availability": "true",
        "include.release.openshift.io/single-node-developer": "true",
        "release.openshift.io/create-only": "true",
        "kubernetes.io/description":
          "restricted denies access to all host features and requires pods to be run with a UID, and SELinux context that are allocated to the namespace.",
      },
      name: "restricted",
      creationTimestamp: "2026-10-01T02:14:00Z",
    },
    priority: null,
    readOnlyRootFilesystem: false,
    requiredDropCapabilities: ["KILL", "MKNOD", "SETUID", "SETGID"],
    runAsUser: {
      type: "MustRunAsRange",
    },
    seLinuxContext: {
      type: "MustRunAs",
    },
    supplementalGroups: {
      type: "RunAsAny",
    },
    users: [],
    volumes: [
      "configMap",
      "csi",
      "downwardAPI",
      "emptyDir",
      "ephemeral",
      "image",
      "persistentVolumeClaim",
      "projected",
      "secret",
    ],
  },
] as Scc[];
