import test from "node:test";
import assert from "node:assert/strict";
import {S,resetState,replaceState} from "../.test-build/src/simulation/state.js";
import {kubeRequest} from "../.test-build/src/simulation/kube-api.js";
import {applyResource,deleteResource,getResources} from "../.test-build/src/simulation/cluster-api.js";
import {clusterCommand} from "../.test-build/src/terminal/cluster-shell.js";
import {authorized} from "../.test-build/src/security/rbac.js";
import {discover} from "../.test-build/src/world/story.js";
import {encodeProgress,decodeProgress} from "../.test-build/src/simulation/snapshot.js";
import {flow} from "../.test-build/src/campaign/models.js";
const api="rbac.authorization.k8s.io/v1";
const pod=(name,ns="team")=>({apiVersion:"v1",kind:"Pod",metadata:{name,namespace:ns},spec:{containers:[{name:"app",image:"busybox"}]}});
const udn=(name="primary",ns="team",subnet="10.80.0.0/24")=>({apiVersion:"k8s.ovn.org/v1",kind:"UserDefinedNetwork",metadata:{name,namespace:ns},spec:{topology:"Layer2",layer2:{role:"Primary",subnets:[subnet]}}});
function namespace(name="team",labelled=false){S.cluster.user="platform-admin";applyResource({apiVersion:"v1",kind:"Namespace",metadata:{name,...(labelled?{labels:{"k8s.ovn.org/primary-user-defined-network":""}}:{})}});}
test("self provisioning uses ProjectRequest, grants admin within that project and cannot create a Namespace",async()=>{
 resetState();assert.equal(authorized("create","namespaces"),false);assert.equal(kubeRequest({method:"POST",path:"/api/v1/namespaces",body:{apiVersion:"v1",kind:"Namespace",metadata:{name:"nope"}}}).code,403);
 const response=await clusterCommand("oc new-project team");assert.equal(response.error??false,false);assert.equal(S.cluster.namespace,"team");assert.equal(authorized("create","pods","team"),true);assert.equal(authorized("create","pods","default"),false);applyResource(pod("hello"),"team");assert.equal(getResources("pods","team","hello")[0].status.phase,"Running");assert.ok(S.cluster.resources.some(r=>r.kind==="RoleBinding"&&r.metadata.namespace==="team"&&r.subjects.some(s=>s.name==="operator")));assert.equal(S.cluster.resources.some(r=>r.kind==="ProjectRequest"),false);
 S.cluster.user="platform-admin";deleteResource("clusterrolebindings","self-provisioners");S.cluster.user="operator";assert.equal(kubeRequest({method:"POST",path:"/apis/project.openshift.io/v1/projectrequests",body:{apiVersion:"project.openshift.io/v1",kind:"ProjectRequest",metadata:{name:"denied"}}}).code,403);
});
test("cluster and tenant bindings apply to any identity and revocation immediately removes authority",()=>{
 resetState();namespace();applyResource({apiVersion:api,kind:"ClusterRole",metadata:{name:"node-reader"},rules:[{apiGroups:[""],resources:["nodes"],verbs:["get","list"]}]});applyResource({apiVersion:api,kind:"RoleBinding",metadata:{name:"ineffective",namespace:"team"},roleRef:{apiGroup:"rbac.authorization.k8s.io",kind:"ClusterRole",name:"node-reader"},subjects:[{kind:"User",name:"auditor"}]},"team");S.cluster.user="auditor";assert.equal(authorized("get","nodes",undefined,"worker-01"),false);S.cluster.user="platform-admin";applyResource({apiVersion:api,kind:"ClusterRoleBinding",metadata:{name:"auditor"},roleRef:{apiGroup:"rbac.authorization.k8s.io",kind:"ClusterRole",name:"node-reader"},subjects:[{kind:"User",name:"auditor"}]});S.cluster.user="auditor";assert.equal(authorized("list","nodes"),true);assert.equal(authorized("patch","nodes",undefined,"worker-01"),false);S.cluster.user="platform-admin";deleteResource("clusterrolebindings","auditor");S.cluster.user="auditor";assert.equal(authorized("list","nodes"),false);
});
test("tenant admin can delegate held permissions, but cannot escalate roles or bind cluster-admin",async()=>{
 resetState();await clusterCommand("oc new-project team");applyResource({apiVersion:api,kind:"Role",metadata:{name:"reader"},rules:[{apiGroups:[""],resources:["pods"],verbs:["get"]}]},"team");applyResource({apiVersion:api,kind:"RoleBinding",metadata:{name:"reader"},roleRef:{apiGroup:"rbac.authorization.k8s.io",kind:"Role",name:"reader"},subjects:[{kind:"User",name:"junior"}]},"team");assert.throws(()=>applyResource({apiVersion:api,kind:"Role",metadata:{name:"escalated"},rules:[{apiGroups:["security.openshift.io"],resources:["securitycontextconstraints"],verbs:["use"]}]},"team"),/attempting to grant/);assert.throws(()=>applyResource({apiVersion:api,kind:"RoleBinding",metadata:{name:"escalated"},roleRef:{apiGroup:"rbac.authorization.k8s.io",kind:"ClusterRole",name:"cluster-admin"},subjects:[{kind:"User",name:"operator"}]},"team"),/attempting to grant/);S.cluster.user="junior";assert.equal(authorized("get","pods","team","hello"),true);assert.equal(authorized("list","pods","team"),false);
});
test("admin credential is physically discovered and survives an offline checkpoint",async()=>{
 resetState();assert.equal((await clusterCommand("oc login -u platform-admin -p training")).error,true);assert.equal((await clusterCommand("oc login -u platform-admin -p training-admin-7f2b9a64c183")).error,true);discover(S,"admin-key");assert.match(S.cluster.files["credentials/platform-admin.txt"],/training-admin-[a-f0-9]+/);replaceState(decodeProgress(encodeProgress(S)));assert.equal((await clusterCommand("oc login -u platform-admin -p training-admin-7f2b9a64c183")).error??false,false);assert.equal(authorized("create","namespaces"),true);assert.equal(authorized("create","clusterrolebindings"),true);
});
test("required SCC and init container security cannot bypass admission; user namespaces have inspectable UID mappings",async()=>{
 resetState();await clusterCommand("oc new-project team");const normal=pod("normal");normal.metadata.annotations={"openshift.io/required-scc":"restricted-v3"};applyResource(normal,"team");assert.equal(getResources("pods","team","normal")[0].spec.hostUsers,false);const map=await clusterCommand("oc exec normal -n team -- cat /proc/self/uid_map");assert.equal(map.error??false,false);const [inside,host,count]=map.stdout.trim().split(/\s+/).map(Number);assert.equal(inside,0);assert.ok(host>=65536);assert.equal(count,65536);
 const hostUsers=pod("host-users");hostUsers.metadata.annotations={"openshift.io/required-scc":"restricted-v3"};hostUsers.spec.hostUsers=true;assert.throws(()=>applyResource(hostUsers,"team"),/hostUsers/);const init=pod("bad-init");init.spec.initContainers=[{name:"setup",image:"busybox",securityContext:{privileged:true}}];assert.throws(()=>applyResource(init,"team"),/initContainers\[0\]/);const denied=pod("ungranted");denied.metadata.annotations={"openshift.io/required-scc":"privileged"};assert.throws(()=>applyResource(denied,"team"),/not usable/);
});
test("UDN label is immutable, a missing label produces SyncError, and labelled Pods wait for a primary network",()=>{
 resetState();namespace("plain");applyResource(pod("old","plain"),"plain");const ip=getResources("pods","plain","old")[0].status.podIP;applyResource(udn("primary","plain"),"plain");assert.equal(getResources("userdefinednetworks","plain","primary")[0].status.conditions[0].reason,"SyncError");assert.equal(getResources("pods","plain","old")[0].status.podIP,ip);assert.throws(()=>applyResource({apiVersion:"v1",kind:"Namespace",metadata:{name:"plain",labels:{"k8s.ovn.org/primary-user-defined-network":""}}}),/immutable/);
 namespace("team",true);applyResource(pod("waiting"),"team");assert.equal(getResources("pods","team","waiting")[0].status.phase,"Pending");assert.equal(getResources("pods","team","waiting")[0].status.podIP,undefined);applyResource(udn(),"team");assert.equal(getResources("userdefinednetworks","team","primary")[0].status.conditions[0].status,"True");assert.equal(getResources("pods","team","waiting")[0].status.phase,"Running");assert.match(getResources("pods","team","waiting")[0].status.podIP,/^10\.80\.0\./);assert.ok(getResources("networkattachmentdefinitions","team","primary")[0].metadata.ownerReferences[0].controller);const changed=udn();changed.spec.layer2.subnets=["10.81.0.0/24"];assert.throws(()=>applyResource(changed,"team"),/immutable/);applyResource(udn("another"),"team");assert.match(getResources("userdefinednetworks","team","another")[0].status.conditions[0].message,/already exist/);
});
test("cluster UDN selects labelled namespaces across tenants and requires cluster authority",()=>{
 resetState();namespace("one",true);namespace("two",true);const net={apiVersion:"k8s.ovn.org/v1",kind:"ClusterUserDefinedNetwork",metadata:{name:"shared"},spec:{namespaceSelector:{matchExpressions:[{key:"kubernetes.io/metadata.name",operator:"In",values:["one","two"]}]},network:{topology:"Layer2",layer2:{role:"Primary",subnets:["10.82.0.0/24"]}}}};S.cluster.user="operator";assert.throws(()=>applyResource(net),/Forbidden/);S.cluster.user="platform-admin";applyResource(net);applyResource(pod("client","one"),"one");applyResource(pod("server","two"),"two");assert.equal(getResources("clusteruserdefinednetworks",undefined,"shared")[0].status.conditions[0].status,"True");assert.equal(flow("one","client","server","two",false,8443),true);
});
