import test from 'node:test';import assert from 'node:assert/strict';
import {S,resetState,replaceState} from '../.test-build/src/simulation/state.js';
import {kubeRequest} from '../.test-build/src/simulation/kube-api.js';
import {clusterCommand} from '../.test-build/src/terminal/cluster-shell.js';
import {observeProcess,baselineFor,setBaselineLocked,baselinePolicyId,execPolicyId} from '../.test-build/src/security/rhacs/runtime.js';
import {encodeProgress,decodeProgress} from '../.test-build/src/simulation/snapshot.js';
import {synchronizeClusterMetadata,getResources,applyResource} from '../.test-build/src/simulation/cluster-api.js';
import {subscribe} from '../.test-build/src/simulation/events.js';
const initialPod=()=>S.cluster.resources.find(r=>r.kind==='Pod'&&r.metadata.name==='payment-api-7d9cd-ab12');
test('exec respects RBAC and emits native-shaped notification evidence only after a successful connection',async()=>{
 resetState();synchronizeClusterMetadata();const events=[];const off=subscribe(e=>{if(e.type==='rhacs.alert')events.push({e,alerts:S.cluster.rhacs.runtime.alerts.length,user:S.cluster.user});});
 const response=await clusterCommand('oc exec payment-api-7d9cd-ab12 -n payments -- curl -I https://203.0.113.77/upload');assert.equal(response.error??false,false);const alert=S.cluster.rhacs.runtime.alerts.find(a=>a.policy.id===execPolicyId);assert.equal(alert.lifecycleStage,'RUNTIME');assert.equal(alert.entityType,'DEPLOYMENT');assert.equal(alert.deployment.name,'payment-api');assert.equal(alert.violations[0].type,'K8S_EVENT');assert.equal(alert.enforcement,undefined);assert.equal(events.length,1);assert.ok(events[0].alerts);assert.ok(initialPod());
 S.cluster.user='unauthorized';assert.equal(kubeRequest({method:'POST',path:'/api/v1/namespaces/payments/pods/payment-api-7d9cd-ab12/exec',body:{command:['id']}}).code,403);assert.equal(alert.violations.length,1);off();
});
test('rsh checks pods/exec and records one exec request, while shell processes use collector observations',async()=>{
 resetState();await clusterCommand('oc rsh -n payments deployment/payment-api');assert.equal(S.cluster.rhacs.runtime.alerts.find(a=>a.policy.id===execPolicyId).violations.length,1);const audits=S.cluster.audit.filter(e=>e.objectRef.subresource==='exec').length;observeProcess(initialPod(),['curl','http://ledger:8443/health']);assert.equal(S.cluster.audit.filter(e=>e.objectRef.subresource==='exec').length,audits);
});
test('unlocked baselines learn names; locked deviations notify and do not kill by default',()=>{
 resetState();synchronizeClusterMetadata();const p=initialPod();observeProcess(p,['java']);observeProcess(p,['curl','/health']);const b=baselineFor(p);assert.deepEqual(b.elements.map(e=>e.element.processName),['java','curl']);assert.equal(S.cluster.rhacs.runtime.alerts.some(a=>a.policy.id===baselinePolicyId),false);setBaselineLocked(b.id,true);observeProcess(p,['/usr/bin/curl','/different-args']);assert.equal(S.cluster.rhacs.runtime.alerts.some(a=>a.policy.id===baselinePolicyId),false);observeProcess(p,['/bin/sh','-c','id'],undefined,['/usr/bin/java']);assert.ok(S.cluster.rhacs.runtime.alerts.find(a=>a.policy.id===baselinePolicyId));assert.ok(S.cluster.rhacs.runtime.alerts.find(a=>a.policy.name==='Shell Spawned by Java Application'));assert.ok(initialPod());
 replaceState(decodeProgress(encodeProgress(S)));assert.equal(S.cluster.rhacs.runtime.baselines[0].userLockedTimestamp,b.userLockedTimestamp);assert.equal(S.cluster.rhacs.runtime.processes.at(-1).signal.lineageInfo[0].parentExecFilePath,'/usr/bin/java');
});
test('configured runtime enforcement removes offending Pod and recreates replicas, retaining its UID in evidence',()=>{
 resetState();synchronizeClusterMetadata();const p=initialPod(),uid=p.metadata.uid;observeProcess(p,['java']);setBaselineLocked(baselineFor(p).id,true);S.cluster.rhacs.policyOverrides[baselinePolicyId]={enforcementActions:['KILL_POD_ENFORCEMENT']};observeProcess(p,['sh','-c','id'],undefined,['/usr/bin/java']);const a=S.cluster.rhacs.runtime.alerts.find(a=>a.policy.id===baselinePolicyId);assert.equal(a.enforcement.action,'KILL_POD_ENFORCEMENT');assert.equal(a.enforcementCount,1);assert.equal(a.processViolation.processes[0].podUid,uid);assert.equal(S.cluster.resources.some(r=>r.kind==='Pod'&&r.metadata.uid===uid),false);assert.equal(getResources('pods','payments').filter(p=>p.metadata.labels?.app==='payment-api').length,2);assert.equal(getResources('deployments','payments','payment-api')[0].status.readyReplicas,2);assert.equal(getResources('endpoints','payments','payment-api')[0].subsets[0].addresses.length,2);
});
test('timemachine separates historical reference events from live state and excludes denied writes',async()=>{
 resetState();const r=await clusterCommand('oc timemachine --auditlog-file ~/forensics/reference-audit.log get deployments -n frontend --time 2025-12-10T06:31:00Z -o json');assert.match(r.stdout,/asset-cache/);assert.equal(S.cluster.resources.some(r=>r.metadata.name==='asset-cache'),false);
 const good={kind:'Event',verb:'create',requestReceivedTimestamp:'2026-10-08T02:00:00Z',objectRef:{resource:'configmaps',namespace:'payments',name:'evidence'},responseStatus:{code:201},responseObject:{apiVersion:'v1',kind:'ConfigMap',metadata:{name:'evidence',namespace:'payments'},data:{value:'initial'}}};S.cluster.files['forensics/test.log']=[good,{...good,verb:'patch',responseStatus:{code:403},responseObject:undefined,requestObject:{data:{value:'denied'}}},{...good,requestReceivedTimestamp:'2026-10-08T03:00:00Z',verb:'delete',responseObject:undefined}].map(e=>JSON.stringify(e)).join('\n');assert.equal(JSON.parse((await clusterCommand('oc timemachine --auditlog-file ~/forensics/test.log get cm evidence -n payments --time 2026-10-08T02:30:00Z -o json')).stdout).data.value,'initial');assert.equal((await clusterCommand('oc timemachine --auditlog-file ~/forensics/test.log get cm evidence -n payments -o json')).stdout,'');
});
