import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { imageAssets } from "../../.test-build/src/security/rhacs/images.js";
import { imageDigestMaterial } from "../../.test-build/src/security/rhacs/digest-material.js";
const digests = Object.fromEntries(
  imageAssets.map((a) => [
    a.ref,
    "sha256:" +
      createHash("sha256").update(imageDigestMaterial(a)).digest("hex"),
  ]),
);
writeFileSync(
  "src/security/rhacs/image-digests.ts",
  "// Generated by tools/roxctl-conformance/hash-images.mjs; SHA-256 of authored artifact contents.\nexport const artifactDigests: Record<string,string> = " +
    JSON.stringify(digests, null, 2) +
    ";\n",
);
console.log(digests);
