// Generated by tools/roxctl-conformance/hash-images.mjs; SHA-256 of authored artifact contents.
export const artifactDigests: Record<string,string> = {
  "registry.example.test/payments:v1.8.2": "sha256:b2a58f1246332c0bf53d407196cbf1ed180ff53836882a2848e415b9ef342d36",
  "registry.example.test/payments:v1.8.3": "sha256:93236ef303d53602bdd15823487a930e4366301acaf2b9a3132292476d063d38",
  "registry.example.test/payments:v1.8.4": "sha256:838945ce4704f6e07b96d6312c771ded5cab3f1332aa4122d118fc34528ac7fc",
  "registry.example.test/private/payments:v1.8.2": "sha256:b2a58f1246332c0bf53d407196cbf1ed180ff53836882a2848e415b9ef342d36",
  "registry.example.test/private/payments:v1.8.3": "sha256:93236ef303d53602bdd15823487a930e4366301acaf2b9a3132292476d063d38",
  "registry.example.test/ledger:v1": "sha256:fdd5701f48c2e19b8e1ec8180d54a182a349120213e8a6b9d8cdcaf2b07a68a3",
  "registry.example.test/owned:arbitrary-uid": "sha256:3e4d8998b7dd3a3b218efc374200e2dcc81e978960db6a2cf666667099125203",
  "registry.example.test/owned:root": "sha256:cd01347455372c49ae6cdc2a56a8c4ca91566ba346096a244936d6f6194938e5",
  "registry.example.test/vendor:fixed-uid": "sha256:25cff32488f93e0d232122f9baf7cba5fbc56a7bdee4c72f9b3bbdb1d136c4c1",
  "quay.io/argoproj/argocd:v3.5.4": "sha256:6677572528f9c9b80e6b5e4e219db480b3730284613e5bea162b4a6f19facc6e",
  "ghcr.io/tektoncd/pipeline/controller:v1.9.0": "sha256:906c4bf0a2182dc673bedbb38b3351ff8a6467cd36241188ed6a16161c1a3b6f",
  "ghcr.io/tektoncd/triggers/controller:v0.35.1": "sha256:f89311f02c2ec0a588acd87533e19ff05b3ff33f6b3a76ba266282be975777e9",
  "quay.io/compliance-operator/compliance-operator:1.8.2": "sha256:0a34de9dd81ada771d346878a9231c47734a1b039685d0f9542cece64bfe3fea",
  "registry.redhat.io/openshift-sandboxed-containers/osc-rhel9-operator:1.11.0": "sha256:338fc983f4a2702a5e877ade3fcb1eadb01cf2dff5898db9700a401a7ba70956",
  "ghcr.io/external-secrets/external-secrets:v0.18.0": "sha256:38f4207ec655575055d286af240b44a075d0979dec95d9d16b0768278d15f023",
  "registry.k8s.io/csi-secrets-store/driver:v1.5.3": "sha256:48ea7179abd65fb4c157010bd6df32823ba00ebc48d9c2badbc67e1256ce2e6e"
};
