// Generated by tools/roxctl-conformance/hash-images.mjs; SHA-256 of authored artifact contents.
export const artifactDigests: Record<string, string> = {
  "registry.example.test/payments:v1.8.2":
    "sha256:b2a58f1246332c0bf53d407196cbf1ed180ff53836882a2848e415b9ef342d36",
  "registry.example.test/payments:v1.8.3":
    "sha256:93236ef303d53602bdd15823487a930e4366301acaf2b9a3132292476d063d38",
  "registry.example.test/payments:v1.8.4":
    "sha256:838945ce4704f6e07b96d6312c771ded5cab3f1332aa4122d118fc34528ac7fc",
  "registry.example.test/private/payments:v1.8.2":
    "sha256:b2a58f1246332c0bf53d407196cbf1ed180ff53836882a2848e415b9ef342d36",
  "registry.example.test/private/payments:v1.8.3":
    "sha256:93236ef303d53602bdd15823487a930e4366301acaf2b9a3132292476d063d38",
  "registry.example.test/ledger:v1":
    "sha256:fdd5701f48c2e19b8e1ec8180d54a182a349120213e8a6b9d8cdcaf2b07a68a3",
  "registry.example.test/owned:arbitrary-uid":
    "sha256:3e4d8998b7dd3a3b218efc374200e2dcc81e978960db6a2cf666667099125203",
  "registry.example.test/owned:root":
    "sha256:cd01347455372c49ae6cdc2a56a8c4ca91566ba346096a244936d6f6194938e5",
  "registry.example.test/vendor:fixed-uid":
    "sha256:25cff32488f93e0d232122f9baf7cba5fbc56a7bdee4c72f9b3bbdb1d136c4c1",
};
